var IALanguage = __ial = {
	
	
    Login:{
    	accnum:'AccountNumber',
    	Sign:'Login'
    },
    Main:{
    	CompareTime:"Start less than end time!",
    	load:"load...",
    	IntelligentAlgorithmManagement:"IntelligentAlgorithm",
    	Tab:{
    		FaceManage:"FaceManage",
    	    PlateManage:"PlateManage"
    	},
    	Algorithm_type:"AlgorithmType",
    	Face_set_name:"FaceSetName",
    	group:"Group",
    	submit:"Submit",
    	add_group:"AddGroup",
    	modify_group:"ModifyGroup",
    	reset:"Reset",
    	add:"Add",
    	modify:"Modify",
    	add_service:"AddServiceAddress",
    	info:"OperationHints",
    	message_input:"Please input the content of asterisk label.",
    	message_ip:"IP address format is incorrect.",
    	message_port:"Port format is incorrect.",
    	same_library:"Have the same address library.",
    	add_library:"AddLibrary",
    	prompt:"You must use letters, numbers, or underlines.",
    	error_message:"The staff member has not been added and cannot be modified！",
    	please_message:"Please input the content of asterisk label.",
    	name_library:"The library name can only be digits, letters, and underlines.",
    	last:"Last",
    	next:"Next",
    	entry_message:"EntryMessage",
    	number:"Number",
    	idNumber:"IDCard",
    	name:"Name",
    	face:"Face",
    	sex:"Sex",
    	male:"male",
    	fomale:"fomale",
    	post:"Job",
    	Project_Department:"ProjectDept",
    	ObjSet:"Gather",
    	Entry_not_modify:"Entry is not modifiable.",
    	number_error:"Number contains illegal characters! Please rewrite it.",
    	idNumber_error:"ID number contains illegal characters! Please rewrite it.",
    	projectDepartment_error:"ProjectDepartment contains illegal characters! Please rewrite it.！",
    	function_error:"function contains illegal characters! Please rewrite it.！",
    	name_error:"name contains illegal characters! Please rewrite it.！",
    	number_err:"Number includes man! Please re write.",
    	idNumber_err:"The ID number includes a man! Please re write.",
    	Algorithm_library_address:"AlgorithmLibraryAddress",
    	Algorithm_library_name:"AlgorithmLibraryName",
    	selectImage:"SelectImage",
    	browse:"Browse",
    	please_select:"Please select a data to operate again.",
    	modify_message:"Modifying basic information",
    	improve_information:"Please improve basic information.",
    	Modifying_supplementary_information:"Modifying supplementary information",
    	Upload_pictures_failed:"Upload pictures failed",
    	Supplementary_personal_information:"Supplementary personal information",
    	complete_supplementary_information:"Please complete the supplementary information.",
    	Already_supplementary_information:"Information has been complementing.",
    	username:"UserName",
    	title:"information",
    	msg:"Successful entry of personnel information",
    	datagrid:{
    		Number:"Number",
    		post:"Post",
    		Project_Department:"ProjectDept",
    		group:"Group",
    		name:"Name",
    		sex:"Sex",
    		JobNumber:"JobNumber",
    		SubcontractTeam:"SubcontractTeam",
    		Dept:"Dept",
    		Company:"Company",
    		BirthDate:"BirthDate",
    		idNumber:"IDCard",
    		personalFile:"PersonalFile",
    		id_a_index:"FrontCard",
    		id_b_index:"ReverseCard",
    		paperPhoto:"PaperPhoto",
    		medicalReport:"MedicalReport",
    		special_permit:"specialPermit",
    		Exam_results:"ExamResult",
    		Audit_status:"AuditStatus",
    		Audit_start:"AuditStartPeriod",
    		Audit_end:"AuditEndPeriod",
    		Auditor:"Auditor",
    		AuditTime:"AuditTime",
    		illegalInformation:"IllegalInformation",
    		description:"Description",
    		end:true
    	},
    	plate:{
    		plate:"Plate",
    		plate_number:"PlateNumber",
    		plate_color:"PlateColor",
    		Vehicle_type:"VehicleType",
    		Vehicle_brand:"VehicleBrand",
    		Vehicle_model:"VehicleModel",
    		trailer_number:"TrailerNumber",
    		trailer_color:"TrailerColor",
    		Add_organization_resources:"AddOrganizationResource",
    		end:true
    	},
    	end:true
    },
    Face:{
    	FaceManagement:"FaceManagement",
    	DataAnalysis:"DataAnalysis",
    	FaceSetManagement:"FaceSetManagement",
    	OrganizationManagement:"OrganizationManagement",
    	Add:"Add",
    	Modify:"Modify",
    	Delete:"Delete",
    	username:"UserName",
    	IDNumber:"IDCard",
    	Number:"Number",
    	FaceScore:"FaceScore",
    	PUID:"PUID",
    	Idx:"Resource Index",
    	Time:"Time",
    	warning:"Warning！",
    	confirm:"Are you sure you want to delete it?",
    	refresh:"refresh",
    	DetectionRecord:"DetectionRecord",
    	IdentificationRecord:"IdentificationRecord",
    	OrganizationCategory:"OrganizationCategory",
    	AddResource:"AddResource",
    	Tips:"Organization category cannot add organizational resources！",
    	DeleteResource:"DeleteResource",
    	Prompt:"Please Input Value",
    	end:true
    },
    Client:{
    	complete:"Complete",
    	info:"OperationHints",
    	message:"The ID and ID account have been registered.！",
    	next:"Next",
    	OrganizationCategory:"OrganizationCategory",
    	end:true
    },
    Car:{
    	LicensePlateManagement:"PlateManagement",
    	LicensePlateAnalysis:"PlateAnalysis",
    	OrganizationManagement:"OrganizationManagement",
    	plate:"Plate",
		plate_number:"PlateNumber",
		plate_color:"PlateColor",
		Vehicle_type:"VehicleType",
		Vehicle_brand:"VehicleBrand",
		Vehicle_model:"VehicleModel",
		trailer_number:"TrailerNumber",
		trailer_color:"TrailerColor",
		Add:"Add",
    	Modify:"Modify",
    	Delete:"Delete",
    	warning:"Warning！",
    	confirm:"Are you sure you want to delete it?",
    	OrganizationCategory:"OrganizationCategory",
    	AddResource:"AddResource",
    	plate:"Plate",
    	Tips:"Organization category cannot add organizational resources！",
    	DeleteResource:"DeleteResource",
    	end:true
    },
    Ajax:{
    	failure:"Ajax fail in send",
    	info:"OperationHints",
    	message:{
    		failure:"failure",
    		exception:"Throwing an Exception",
    		logged:"The system has been logged in.",
    		notlogged:"System is not logged in.",
    		action_error:"Error in request method name",
    		action_noKnown:"The requested method name is unknown.",
    		action_noExists:"The request method name does not exist.",
    		content_error:"Request parameter error",
    		content_noKnown:"Unknown request parameters",
    		content_noExists:"The request parameter does not exist.",
    		offset_max:"offset Oversize",
    		content_wrongful:"Invalid request parameters",
    		mysql_object:"MYSQL database connection instance object creation failed",
    		mysql_operation:"MYSQL database operation failed",
    		WebService_request_error:"WebService request address error",
    		WebService_password_error:"WebService password verification error",
    		WebService_response_error:"WebService Response failure",
    		WebService_content_error:"WebService Parameter validation failed",
    		WebService_object_error:"WebService Object is not instantiated",
    		login_failure:"Login failure",
    		login_overtime:"login timeout",
    		login_Username_format_error:"Login user name format error",
    		login_Username_noExists:"Login user name does not exist.",
    		login_password_error:"Login password error",
    		login_Username_content_wrongful:"Login user name parameter is not valid.",
    		login_max_offset:"Login exceeds the maximum number of connections",
    		session_faulure:"SESSION ERROR",
    		session_lose:"SESSION Invalid",
    		session_wrongful:"SESSION Length is not legal.",
    		PLAT_NOT_LOGIN:"GSOAP is not logged in.",
    		PLAT_ALREADY_LOGIN:"GSOAP is already logged in",
    		UPLOAD_ERROR:"Upload error",
    		UPLOAD_PHOTO_EXT_ERROR:"Upload file format error",
    		XML_REQUEST_NU_FORMAT_ERROR:"XML Request Message Format Error",
    		XML_RESPONSE_NU_ERROR:"NU error of XML response message",
    		XML_RESPONSE_NU_TIMEOUT:"XML response message NU timeout",
    		REMOTE_SERVER_REQUEST_ERROR:"Remote server response failed",
    		xml_send_error:"XML Failure to send to remote server",
    		xml_analysis_error:"XML Message parsing failed",
    		xml_return_error:"XML Return error",
    		xml_send_OPTID:"XML Send OPTID Error",
    		xml_NU_error:"XML Message NU Error",
    		Equipment_not_online:"Equipment not online",
    		Request_flow_IPTOKEN_failed:"Request flow IPTOKEN Failure",
    		Request_real_time_stream_RTMP_failed:"Request real-time stream RTMP Failure",
    		Play_RTMP_stream_failed:"Play RTMP Stream Failure",
    		Stop_RTMP_stream_failed:"Stop RTMPS tream Failure"
    		
    	}
    },
    
    end:true
}